Ftraining dev
JugglypuffM/Health-App-Server pull request #11
Opened 2024-12-06 14:01 UTC by AHDEPCEH

Тут есть 2 ошибки с классом Training, я не понимаю, что там не так. Посмотри пожалуйста
А так всю реализацию я сделал, но ничего не тестировал

2024-12-06 15:14 UTC, AHDEPCEH commented
Поправил конструктор

2024-12-21 07:02 UTC, AHDEPCEH commented
Сделал merge через идею

2024-12-21 14:54 UTC, JugglypuffM requested changes
Нашлось немало проблем

2024-12-21 14:54 UTC, JugglypuffM commented on src/main/kotlin/database/tables/TrainingTable.kt
> +    val loginID = optReference(name="FK_loginID", UsersTable.id, onDelete = ReferenceOption.CASCADE)
Что еще за loginId - у нас же логин это и есть Id

Я возможно чего-то не понял, но в UsersTable даже нет поля Id

2024-12-21 14:54 UTC, JugglypuffM commented on src/main/kotlin/domain/user/UserInfo.kt
> +    val level: Int,
Что еще за несогласованное изменение доменной модели?

Если хочешь что-то изменить, то во-первых, нужно нам об этом сказать, а то в приложении вроде даже нет никакой обработки данных об "уровне", а во-вторых, не заменяй сущности которые уже используются - тебе недостаточно просто поменять название, потому что дистанция призвана обновляться придобавлении тренировки типа jogging и в ней, по очевидным причинам, содержится расстояние, а уровень это что-то совсем другое, но в итоге из-за того что было изменено только название поле с уровнем будет все еще хранить расстояние, только смысл теперь не понятен

2024-12-21 15:43 UTC, JugglypuffM commented
Поменяй еще названия пр-а - некрасиво же))))

2024-12-23 14:57 UTC, AHDEPCEH commented on src/main/kotlin/database/manager/DatabaseManagerService.kt
> +    private val url = dotenv()["PSQL_URL"].toString()
К слову, я сделал так как ты меня просил.

2024-12-23 14:59 UTC, AHDEPCEH commented on src/main/kotlin/database/dao/DAO.kt
Если речь про интерфейс, то он просто мешается, он накидывает очень много ограничений для тех, кто его использует. Поэтому ради расширяемости кода он был удалён

2024-12-23 15:02 UTC, AHDEPCEH commented on src/main/kotlin/database/exception/DatabaseException.kt
Не вижу тут проблемы. Да, как оно было реализовано до этого, так было действительно лучше, но теперь интерфейса нет, следовательно объединять незачем. Можно конечно ввести интерфейс, без методов, но какой в этом смысл. Таких объектов будет не много, да и другие с ними не работают. А менеджеру бд вообще это никак не мешает.

2024-12-23 15:04 UTC, AHDEPCEH commented on src/main/kotlin/database/manager/DatabaseManagerService.kt
> +    private val url = dotenv()["PSQL_URL"].toString()
То что ты мне предложил не несёт опять же практичности. В чём проблема указывать полный url чтобы можно было подключаться не только к бд постгреса, как ты этого хочешь?

2024-12-23 15:10 UTC, JugglypuffM commented on src/main/kotlin/database/dao/DAO.kt
он нужен как раз для ограничений, для полиморфности кода, к тому же чем он тебе мешал?

2024-12-23 15:19 UTC, AHDEPCEH commented on src/main/kotlin/database/tables/TrainingTable.kt
> +    val additionalData: Column<String?> = varchar("additional_data", 255).nullable()
Идея хорошая, но не совсем, объясняю почему:
1) как я представлял изначально, у нас должно получиться что-то типо трекера. То есть и тренировки подразумевают наличие дистанции. Правда, мы кажется отошли от своей идеи. То что ты предложил не имеет смысла, потому что эти данные не возможно сохранить в реляционной базе данных, поэтому там и есть дополнительная колонка. По факту нужно тогда просто убрать из таблицы дистанцию и сохранять это как отдельные параметры тренировки.
2) хранить тип тренировки по индексу это да, отличная идея и я так и хотел сделать. Но реализация немного сложноватая, поэтому решил упростить.

2024-12-23 15:21 UTC, JugglypuffM commented on src/main/kotlin/database/exception/DatabaseException.kt
> как оно было реализовано до этого, так было действительно лучше

так зачем ты это убрал
понятное дело что можно вообще как угодно писать и в маленьких масштабах оно будет лучше, но писать то лучше чтобы оно масштабировалось

2024-12-23 15:21 UTC, AHDEPCEH commented on src/main/kotlin/database/dao/DAO.kt
Я знаю для чего нужны интерфейсы. А мешал он тем, что эти объекты не имеют ничего схожего кроме схожего конструктора

2024-12-23 15:22 UTC, AHDEPCEH commented on src/main/kotlin/database/exception/DatabaseException.kt
Читай сообщение полностью, я же объяснил для чего.

2024-12-23 15:24 UTC, JugglypuffM commented on src/main/kotlin/database/tables/TrainingTable.kt
> +    val additionalData: Column<String?> = varchar("additional_data", 255).nullable()
> эти данные не возможно сохранить в реляционной базе данных

это еще почему?

2024-12-23 15:25 UTC, JugglypuffM commented on src/main/kotlin/database/tables/TrainingTable.kt
> +    val additionalData: Column<String?> = varchar("additional_data", 255).nullable()
> сложноватая

максимум понимания, минимум обсуждения - сделай если будет время

2024-12-23 15:30 UTC, AHDEPCEH commented on src/main/kotlin/database/tables/TrainingTable.kt
> +    val loginID = optReference(name="FK_loginID", UsersTable.id, onDelete = ReferenceOption.CASCADE)
Как раз таки есть

2024-12-23 15:31 UTC, JugglypuffM commented on src/main/kotlin/database/exception/DatabaseException.kt
> Читай сообщение полностью, я же объяснил для чего.

а я ответил почему твое объяснение меня не устраивает

2024-12-23 15:31 UTC, AHDEPCEH commented on src/main/kotlin/database/dao/DAO.kt
Так в этом и проблема, что не получается подогнать объекты под эти критерии

2024-12-23 15:32 UTC, AHDEPCEH commented on src/main/kotlin/database/dao/DAO.kt
Уменьшить количество критериев не решит проблему в будущем, вот так и получается

2024-12-23 15:34 UTC, JugglypuffM commented on src/main/kotlin/database/tables/TrainingTable.kt
> +    val loginID = optReference(name="FK_loginID", UsersTable.id, onDelete = ReferenceOption.CASCADE)
экспоузд сам определяет его?
```
object UsersTable : IntIdTable() {
    val login : Column<String> = varchar("u_login", 45).uniqueIndex()
    val password : Column<String> = varchar("u_password", 35)
    val name : Column<String> = varchar("u_name", 20)
    val age : Column<Int> = integer("age")
    val weight : Column<Int> = integer("weight")
    val distance : Column<Int> = integer("distance")
    val level : Column<Int> = integer("level")
}
```
потому что тут я его не вижу

2024-12-23 15:37 UTC, AHDEPCEH commented on src/main/kotlin/database/exception/DatabaseException.kt
Как ты предлагаешь, чтобы я решил это?

2024-12-23 15:38 UTC, AHDEPCEH commented on src/main/kotlin/database/manager/DatabaseManagerService.kt
> +    private val url = dotenv()["PSQL_URL"].toString()
А, ну тогда нужно просто переименовать параметр .env и всё

2024-12-23 15:39 UTC, AHDEPCEH commented on src/main/kotlin/database/manager/DatabaseManagerService.kt
> +    private val trainingDAO: TrainingDAO
Тут как я понимаю вопрос тоже решён

2024-12-23 15:40 UTC, AHDEPCEH commented on src/main/kotlin/database/tables/TrainingTable.kt
> +    val loginID = optReference(name="FK_loginID", UsersTable.id, onDelete = ReferenceOption.CASCADE)
Там типо прикол с типом таблицы: IntIdTable там под копотом он создаётся как интовый первичный ключ

2024-12-23 15:41 UTC, JugglypuffM commented on src/main/kotlin/database/exception/DatabaseException.kt
> Читай сообщение полностью, я же объяснил

)))

А если серьезно, то я действительно уже написал:

> Нужно их как минимум в один файл объеденить

2024-12-23 15:42 UTC, AHDEPCEH commented on src/main/kotlin/domain/user/UserInfo.kt
> +    val level: Int,
В этом и проблема, смысл хранить дистанцию в информации о пользователе это как-то странно. Там изначально должен был быть уровень пользователя или типо того.

2024-12-23 15:43 UTC, JugglypuffM commented on src/main/kotlin/database/exception/DatabaseException.kt
дело опять же не первостепенной важности и вообще не критичное

2024-12-23 15:43 UTC, AHDEPCEH commented on src/main/kotlin/database/exception/DatabaseException.kt
Кого их то?

2024-12-23 15:44 UTC, JugglypuffM commented on src/main/kotlin/database/manager/DatabaseManagerService.kt
> +    private val url = dotenv()["PSQL_URL"].toString()
да, именно это я и предложил в качестве второго варианта в первом сообщении - большего не требую

2024-12-23 15:44 UTC, JugglypuffM commented on src/main/kotlin/database/manager/DatabaseManagerService.kt
> +    private val trainingDAO: TrainingDAO
да

2024-12-23 15:44 UTC, AHDEPCEH commented on src/main/kotlin/database/tables/TrainingTable.kt
> +    val additionalData: Column<String?> = varchar("additional_data", 255).nullable()
Потому что чтобы что-то сохранить в бд у этих объектов нужно выделить общие черты и параметры. Если этого не получается сделать, то в реляционную бд его не сохранить. Поэтому тут надо исхитряться.

2024-12-23 15:45 UTC, JugglypuffM commented on src/main/kotlin/database/tables/TrainingTable.kt
> +    val loginID = optReference(name="FK_loginID", UsersTable.id, onDelete = ReferenceOption.CASCADE)
мы же вроде договаривались логин в качестве id использовать еще на созвоне?

2024-12-23 15:46 UTC, JugglypuffM commented on src/main/kotlin/domain/user/UserInfo.kt
> +    val level: Int,
зачем вообще хранить какую-лио информацию о пользователе - для статистики
плюс главная проблема все же в том, что я об этом случайно узнал, при чем в тот момент, когда на своей стороне реализовал уже все под distance

2024-12-23 15:48 UTC, AHDEPCEH commented on src/main/kotlin/database/tables/TrainingTable.kt
> +    val loginID = optReference(name="FK_loginID", UsersTable.id, onDelete = ReferenceOption.CASCADE)
Ну, он и будет как id только с точки зрения нормирования базы данных, это неправильный подход. Потому что иначе будет проблемно создавать связи между табличками.
Да и это уже вопрос к бд, к её оптимизации памяти

2024-12-23 15:49 UTC, JugglypuffM commented on src/main/kotlin/database/tables/TrainingTable.kt
> +    val additionalData: Column<String?> = varchar("additional_data", 255).nullable()
и решение этому я тебе тоже уже предложил: партицируй несмежные для типов тренировок черты и параметры, выдели каждую специфическую информацию в отдельную таблицу

_...почему мне приходится пересказывать свои сообщения?_

2024-12-23 15:51 UTC, AHDEPCEH commented on src/main/kotlin/domain/user/UserInfo.kt
> +    val level: Int,
Ну, это не долго исправить. Тут же просто достаточно обойтись переименованием. Но а как иначе, не будешь же там хранить дистанцию, это тупо не имеет смысла

2024-12-23 15:51 UTC, JugglypuffM commented on src/main/kotlin/database/tables/TrainingTable.kt
> +    val loginID = optReference(name="FK_loginID", UsersTable.id, onDelete = ReferenceOption.CASCADE)
хорошо, сейчас я не могу сходу придумать проблем. которые данная реализация может вызвать, так что просто буду надеяться что это не вызовет проблем

2024-12-23 15:51 UTC, AHDEPCEH commented on src/main/kotlin/database/tables/TrainingTable.kt
> +    val loginID = optReference(name="FK_loginID", UsersTable.id, onDelete = ReferenceOption.CASCADE)
Логин так и остался уникальным, поэтому тут всё ок по факту.

2024-12-23 15:52 UTC, JugglypuffM commented on src/main/kotlin/domain/user/UserInfo.kt
> +    val level: Int,
просто добавь новое поле level и сохрани старое distance - поддержку я потом докину

2024-12-23 15:53 UTC, AHDEPCEH commented on src/main/kotlin/database/tables/TrainingTable.kt
> +    val additionalData: Column<String?> = varchar("additional_data", 255).nullable()
Вот только проблема заключается в том, что таких черт нихера и нет, так как я без понятия какие тренировки у нас будут ещё и что там в них сохранять

2024-12-23 15:53 UTC, JugglypuffM commented on src/main/kotlin/domain/user/UserInfo.kt
> +    val level: Int,
в прочем странно что ты начал пропихивать новую бизнес логику, хотя мы пока даже не планировали
я бы вообще без уровней пока обошелся

2024-12-23 15:54 UTC, JugglypuffM commented on src/main/kotlin/domain/user/UserInfo.kt
> +    val level: Int,
я про то, что сейчас у нас даже нет понимания что такое уровень и как его считать - это нужно накидывать новую логику

2024-12-23 15:54 UTC, AHDEPCEH commented on src/main/kotlin/database/tables/TrainingTable.kt
> +    val additionalData: Column<String?> = varchar("additional_data", 255).nullable()
Тут надо создавать не отдельную таблицу, а отдельные таблицы для каждого типа тренировок и там уже сохранять все возможные доп параметры, а это какая-то херня

2024-12-23 15:55 UTC, JugglypuffM commented on src/main/kotlin/database/tables/TrainingTable.kt
> +    val additionalData: Column<String?> = varchar("additional_data", 255).nullable()
> без понятия какие тренировки у нас будут ещё и что там в них сохранять

плюс предложенного подхода как раз в том, что тебе и не надо

2024-12-23 15:56 UTC, AHDEPCEH commented on src/main/kotlin/domain/user/UserInfo.kt
> +    val level: Int,
Так дистанцию всё равно придётся от туда убирать, правильно же? Тогда не проще ли просто переименовать? А как считать уровень, это уже потом разберёмся

2024-12-23 15:57 UTC, JugglypuffM commented on src/main/kotlin/database/tables/TrainingTable.kt
> +    val additionalData: Column<String?> = varchar("additional_data", 255).nullable()
> не отдельную таблицу, а отдельные таблицы

слишком уж много в этом конкретном конверсе поднимается тема непрочтения сообщений:

> каждую специфическую информацию в отдельную таблицу

каждую информацию -> в отдельную таблицу: я буквально это и предложил

2024-12-23 15:58 UTC, JugglypuffM commented on src/main/kotlin/domain/user/UserInfo.kt
> +    val level: Int,
> Так дистанцию всё равно придётся от туда убирать, правильно же?

> и сохрани старое distance

я просто оставлю это здесь

2024-12-23 15:59 UTC, JugglypuffM commented on src/main/kotlin/domain/user/UserInfo.kt
> +    val level: Int,
и объясню, чтобы не допустить недопониманий: нет, раз уж мы добавили дистанция - значит она остается, потому что почему бы и нет, в конце концов ее можно будет использовать как параметр увеличения уровня

2024-12-23 16:02 UTC, AHDEPCEH commented on src/main/kotlin/database/tables/TrainingTable.kt
> +    val additionalData: Column<String?> = varchar("additional_data", 255).nullable()
Ты мне предложил создать одну таблицу и туда всё занести:/

2024-12-23 16:04 UTC, AHDEPCEH commented on src/main/kotlin/domain/user/UserInfo.kt
> +    val level: Int,
Так в этом просто нет смысла, потому что это несёт только дополнительные расходы памяти, а пользы ноль

2024-12-23 16:05 UTC, AHDEPCEH commented on src/main/kotlin/domain/user/UserInfo.kt
> +    val level: Int,
Может пользователь вообще не будет пользоваться тренировками, где есть дистанция

2024-12-23 16:06 UTC, JugglypuffM commented on src/main/kotlin/database/tables/TrainingTable.kt
> +    val additionalData: Column<String?> = varchar("additional_data", 255).nullable()
я видимо непонятно объсняю)
в общем: я предлагаю _специфическую информацию для конкретной тренировки_ вынести в **отдельную таблицу** _для этой конкретной тренировки_, то есть для ёги будет таблица с потенциальным ничем(отсутствие таблицы) или если мы захотим к ней чтото добавить - вся информация будет тусовать в этой конкретной таблице, а для жогинга будет отдельная таблица с условной дистанцией, высотой и тд. Так и для всех других видов, потому что иначе мне организация данных возможной не представляется

P.S: в реляционной базе, потому что в nosql можно херачить в жысоны и горя не знать, но это выходит за рамки нашей досягаемости)

2024-12-23 16:06 UTC, AHDEPCEH commented on src/main/kotlin/domain/user/UserInfo.kt
> +    val level: Int,
Хотя ладно, я придумал, как это можно использовать, пусть будет

2024-12-23 16:08 UTC, JugglypuffM commented on src/main/kotlin/domain/user/UserInfo.kt
> +    val level: Int,
ну и пусть, она просто будет равна нулю для него, за то нулю не будут равны другие показатели
с такой логикой можно вообще даже тренировки все удалить, потому что а вдруг ими пользоваться не будут)
к тому же с другой стороны твоего примера чиллят бегуны, которые хотели бы увидеть сколько они набегали

2024-12-23 16:09 UTC, AHDEPCEH commented on src/main/kotlin/database/tables/TrainingTable.kt
> +    val additionalData: Column<String?> = varchar("additional_data", 255).nullable()
Ну собственно да, так я и видел решение этой проблемы. Но это пиздец сколько там работы

2024-12-23 16:11 UTC, AHDEPCEH commented on src/main/kotlin/domain/user/UserInfo.kt
> +    val level: Int,
Бегунам конечно это будет классно знать, вот только они в рот возьмут у велосипедистов или т.п хахпхпхха

2024-12-23 16:11 UTC, AHDEPCEH commented on src/main/kotlin/domain/user/UserInfo.kt
> +    val level: Int,
Ну это я так, просто к слову, пусть будет дистанция

2024-12-23 16:12 UTC, JugglypuffM commented on src/main/kotlin/database/tables/TrainingTable.kt
> +    val additionalData: Column<String?> = varchar("additional_data", 255).nullable()
зато красиво и удобно

2024-12-23 16:12 UTC, JugglypuffM commented on src/main/kotlin/database/tables/TrainingTable.kt
> +    val additionalData: Column<String?> = varchar("additional_data", 255).nullable()
сделать это я уже считаю необходимым, если не согласен - надо будет спросить мнения артема

2024-12-23 20:43 UTC, JugglypuffM commented
Еще не забудь смерджить базу в памяти в дев, потом сюда и актуализировать - чтобы тренировки сохраняла

2024-12-27 09:32 UTC, JugglypuffM commented
и еще это, добавь установку дистанции в 0 сразу при создании пользователя, чтобы не было казусов с нулл поинтерами
(потому что я на момент написания кода не учитывал такую возможность)

2024-12-27 13:22 UTC, JugglypuffM approved these changes

2024-12-27 13:22 UTC, merged